### ISSUE TITLE
Depending on variable hoisting 

### ISSUE THREAD

**Issue by rizowski** [LeisureLink/magicbus#23]
There are several examples in this project that is depending on javascript's variable hoisting.

`module.exports = <exported-object>` should be defined at the bottom.

https://github.com/LeisureLink/magicbus/blob/master/lib/binder.js#L6

```
'use strict';

module.exports = Binder; // <-- Binder is undefined on assignment in future versions of javascript

function Binder(){ ... } // <-- Binder variable is hoisted above module.exports.
```

Javascript the good parts indicates that depending on variable hoisting as a bad practice.

**Comment by twindagger** [comment]
I think i've fixed all of these - let me know if I missed one
