### ISSUE TITLE
Magicbus swallows errors 

### ISSUE THREAD

**Issue by rizowski** [LeisureLink/magicbus#29]
This isn't too good when you are depending on errors to be thrown if something goes wrong.

It is causing code such as:
```js
subscriber.on('some.event', (event, data) =>{
  try {
     // It is supposed to throw to fail the test. 
     // Doesn't bubble up without try catch and done
    expect(data).to.be.ok;
  } catch(e) {
    done(e);
  }
  done();
});
```
https://github.com/LeisureLink/courier/blob/master/tests/integration/rates-integration-test.js#L74-L79

**Comment by twindagger** [comment]
Try after #32 please

**Comment by twindagger** [comment]
Closing after a month of inactivity
